export const SET_THEME = "APP/SET_THEME";
export const SHOW_LOADER = "APP/SHOW_LOADER";
export const HIDE_LOADER = "APP/HIDE_LOADER";
export const RESET_EMPLOYEE_COUNT_TO_SHOW =
  "EMPLOYEE/RESET_EMPLOYEE_COUNT_TO_SHOW";
export const INCREASE_EMPLOYEE_COUNT_TO_SHOW =
  "EMPLOYEE/INCREASE_EMPLOYEE_COUNT_TO_SHOW";
export const HANDLE_INCREASE_EMPLOYEE_COUNT_TO_SHOW =
  "EMPLOYEE/HANDLE_INCREASE_EMPLOYEE_COUNT_TO_SHOW";
