export const mockEmployeeList = [
  {
    id: 1,
    imgUrl: "/assets/photos/team_person_1.jpg",
    name: "Sargis Grigor",
    position: "Data analyst",
  },
  {
    id: 2,
    imgUrl: "/assets/photos/team_person_2.jpg",
    name: "Bagrat Leo",
    position: "Data engineer",
  },
  {
    id: 3,
    imgUrl: "/assets/photos/team_person_3.jpg",
    name: "Gor Sargis",
    position: "Data analyst",
  },
  {
    id: 4,
    imgUrl: "/assets/photos/team_person_4.jpg",
    name: "Maral Mari",
    position: "Data analyst",
  },
  {
    id: 5,
    imgUrl: "/assets/photos/team_person_5.jpg",
    name: "Hakob Jirair",
    position: "Data engineer",
  },
  {
    id: 6,
    imgUrl: "/assets/photos/team_person_6.jpg",
    name: "Eva Vosgi",
    position: "Data scientist ",
  },
  {
    id: 7,
    imgUrl: "/assets/photos/team_person_7.jpg",
    name: "Kohar Marine",
    position: "Data scientist ",
  },
  {
    id: 8,
    imgUrl: "/assets/photos/team_person_8.jpg",
    name: "Ararat Ohannes",
    position: "Data analyst",
  },
  {
    id: 9,
    imgUrl: "/assets/photos/team_person_9.jpg",
    name: "Eduard Vosgi",
    position: "Data scientist ",
  },
  {
    id: 10,
    imgUrl: "/assets/photos/team_person_1.jpg",
    name: "Sargis Grigor",
    position: "Data analyst",
  },
  {
    id: 11,
    imgUrl: "/assets/photos/team_person_2.jpg",
    name: "Bagrat Leo",
    position: "Data engineer",
  },
  {
    id: 12,
    imgUrl: "/assets/photos/team_person_3.jpg",
    name: "Gor Sargis",
    position: "Data analyst",
  },
  {
    id: 13,
    imgUrl: "/assets/photos/team_person_4.jpg",
    name: "Maral Mari",
    position: "Data analyst",
  },
  {
    id: 14,
    imgUrl: "/assets/photos/team_person_5.jpg",
    name: "Hakob Jirair",
    position: "Data engineer",
  },
  {
    id: 15,
    imgUrl: "/assets/photos/team_person_6.jpg",
    name: "Eva Vosgi",
    position: "Data scientist ",
  },
  {
    id: 16,
    imgUrl: "/assets/photos/team_person_7.jpg",
    name: "Kohar Marine",
    position: "Data scientist ",
  },
  {
    id: 17,
    imgUrl: "/assets/photos/team_person_8.jpg",
    name: "Ararat Ohannes",
    position: "Data analyst",
  },
  {
    id: 18,
    imgUrl: "/assets/photos/team_person_9.jpg",
    name: "Eduard Vosgi",
    position: "Data scientist ",
  },
  {
    id: 19,
    imgUrl: "/assets/photos/team_person_1.jpg",
    name: "Sargis Grigor",
    position: "Data analyst",
  },
  {
    id: 20,
    imgUrl: "/assets/photos/team_person_2.jpg",
    name: "Bagrat Leo",
    position: "Data engineer",
  },
  {
    id: 21,
    imgUrl: "/assets/photos/team_person_3.jpg",
    name: "Gor Sargis",
    position: "Data analyst",
  },
  {
    id: 22,
    imgUrl: "/assets/photos/team_person_4.jpg",
    name: "Maral Mari",
    position: "Data analyst",
  },
  {
    id: 23,
    imgUrl: "/assets/photos/team_person_5.jpg",
    name: "Hakob Jirair",
    position: "Data engineer",
  },
];

export const mockPosts = [
  {
    id: 1,
    imgUrl: "/assets/photos/img_1.jpg",
    date: "22 June 2022",
    header: "Sed ut perspiciatis unde omnis at vero blanditils",
    text: "Mauris purus diam, iaculis non leo nec, ultricies fringilla odio. Fusce feugiat elit facilisis volutpat venenatis. Vestibulum tempor ligula vel orci consectetur, euismod augue bibendum...",
    author: "Hakob Jirair",
    views: 450,
    tags: ["App", "Data"],
  },
  {
    id: 2,
    imgUrl: "/assets/photos/img_2.jpg",
    date: "22 June 2022",
    header: "ISO 13485 compliance of medical devices",
    text: "Mauris purus diam, iaculis non leo nec, ultricies fringilla odio. Fusce feugiat elit facilisis volutpat venenatis. Vestibulum tempor ligula vel orci consectetur, euismod augue bibendum...",
    author: "Maral Mari",
    views: 420,
    tags: ["Management", "CMR", "CIO"],
  },
  {
    id: 3,
    imgUrl: "/assets/photos/img_3.jpg",
    date: "22 June 2020",
    header: "Business analysis helps you  in finance",
    text: "Mauris purus diam, iaculis non leo nec, ultricies fringilla odio. Fusce feugiat elit facilisis volutpat venenatis. Vestibulum tempor ligula vel orci consectetur, euismod augue bibendum...",
    author: "Bagrat Leo",
    views: 1420,
    tags: ["Management", "CMR", "CIO"],
  },
  {
    id: 4,
    imgUrl: "/assets/photos/img_15.jpg",
    date: "22 June 2022",
    header: "Benefits of telemedicine in nursing homes",
    text: "Mauris purus diam, iaculis non leo nec, ultricies fringilla odio. Fusce feugiat elit facilisis volutpat venenatis. Vestibulum tempor ligula vel orci consectetur, euismod augue bibendum...",
    author: "Bagrat Leo",
    views: 987,
    tags: ["Management", "CMR", "CIO"],
  },
  {
    id: 5,
    imgUrl: "/assets/photos/img_16.jpg",
    date: "22 June 2022",
    header: "5 web portal examples your business can learn from",
    text: "Mauris purus diam, iaculis non leo nec, ultricies fringilla odio. Fusce feugiat elit facilisis volutpat venenatis. Vestibulum tempor ligula vel orci consectetur, euismod augue bibendum...",
    author: "Bagrat Leo",
    views: 678,
    tags: ["Management", "CMR", "CIO"],
  },
  {
    id: 6,
    imgUrl: "/assets/photos/img_13.jpg",
    date: "22 June 2022",
    header: "5 web portal examples your business can learn from",
    text: "Mauris purus diam, iaculis non leo nec, ultricies fringilla odio. Fusce feugiat elit facilisis volutpat venenatis. Vestibulum tempor ligula vel orci consectetur, euismod augue bibendum...",
    author: "Bagrat Leo",
    views: 31,
    tags: ["Management", "CMR", "CIO"],
  },
  {
    id: 7,
    imgUrl: "/assets/photos/img_14.jpg",
    date: "22 June 2022",
    header: "5 web portal examples your business can learn from",
    text: "Mauris purus diam, iaculis non leo nec, ultricies fringilla odio. Fusce feugiat elit facilisis volutpat venenatis. Vestibulum tempor ligula vel orci consectetur, euismod augue bibendum...",
    author: "Bagrat Leo",
    views: 20,
    tags: ["Management", "CMR", "CIO"],
  },
  {
    id: 8,
    imgUrl: "/assets/photos/img_16.jpg",
    date: "22 June 2022",
    header: "5 web portal examples your business can learn from",
    text: "Mauris purus diam, iaculis non leo nec, ultricies fringilla odio. Fusce feugiat elit facilisis volutpat venenatis. Vestibulum tempor ligula vel orci consectetur, euismod augue bibendum...",
    author: "Bagrat Leo",
    views: 817,
    tags: ["Management", "CMR", "CIO"],
  },
];
